module.exports = {
  HTTP_CODE_SUCCESS: 200,
  HTTP_CODE_CREATE_SUCCESS: 201,

  HTTP_CODE_BAD_REQUEST: 400,
  HTTP_CODE_UNAUTHORIZED: 401,
  HTTP_CODE_FORBIDDEN: 403,
  HTTP_CODE_NOT_FOUND: 404,
  HTTP_CODE_CONFLICT: 409,

  HTTP_CODE_INTERNAL_SERVER_ERROR: 500,
};
